name: normalize composer.json

on:
  workflow_call:
    inputs:
      php:
        default: "8.1"
        type: string

jobs:
  normalize:
    if: ${{ github.actor != 'dependabot[bot]' }}
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Validate Composer configuration
        run: composer validate --strict

      - name: Install dependencies
        uses: "ramsey/composer-install@v2"

      - name: Normalize composer.json
        run: composer normalize --indent-style=space --indent-size=4 --no-check-lock --no-update-lock --no-interaction --ansi
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: >
            chore: normalize composer.json
