name: phpstan

on:
  workflow_call:

jobs:
  phpstan:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.1]
        laravel: [10.*]
        dependency-version: [prefer-stable]
        include:
          - composer-options: "--ignore-platform-reqs"
    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo, pdo_sqlite
          coverage: none
      - name: Install dependencies
        uses: "ramsey/composer-install@v2"
        with:
          composer-options: "${{ matrix.composer-options }}"
      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
