name: pint

on:
  workflow_call:
    inputs:
      php:
        default: "8.1"
        type: string

jobs:
  pint:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none
      - name: Install dependencies
        uses: "ramsey/composer-install@v2"
      - name: Run Pint
        run: ./vendor/bin/pint
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: >
            style: apply pint code style
